#------------------------------------------------------------------------------
# Author: Lavi Jain
# Created: 06-02-2024
# Copyright 2023 by Espire Infolabs
#------------------------------------------------------------------------------
version: '3'
#all port number should be exposed appending
services:

  muuvr:
    image: deebendu/muuvr:latest
    container_name: muuvr
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ${DATA}/app/config:/opt/service/config
      - ${DATA}/app/certs:/opt/service/certs
      - ${DATA}/app/trace:/opt/service/trace
    networks:
      - portainer

  react-muuvr:
    image: deebendu/react-muuvr:latest
    container_name: react-muuvr
    restart: on-failure
    ports:
      - "8001:8001"
    volumes:
      - /opt/container/muuvr/muuvrui/conf.d:/etc/nginx/conf.d
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true
