#------------------------------------------------------------------------------
# Author: Deebendu Kumar
# Created: 17-10-2023
# Copyright 2023 by Espire Infolabs
#------------------------------------------------------------------------------
version: '3'
#all port number should be exposed appending 9
services:

  mariadb:
    image: library/mariadb:10
    container_name: mariadb
    volumes:
      - ${DATA}/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: KeycloakDB
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
    networks:
      - portainer

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    restart: unless-stopped
    volumes:
      - ./certs:/opt/jboss/keycloak/certs
    ports:
      - "6443:8443"
    environment:
      KEYCLOAK_LOGLEVEL: DEBUG
      DB_VENDOR: mariadb
      DB_ADDR: mariadb
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: KeycloakDB
      DB_PORT: 3306
      KEYCLOAK_USER: admin
      #KEYCLOAK_PASSWORD: Pa55w0rd
      #KEYCLOAK_STATISTICS: all
    depends_on:
      - mariadb
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true
