#------------------------------------------------------------------------------
# Author: Deebendu Kumar
# Created: 17-10-2023
# Copyright 2023 by Espire Infolabs
#------------------------------------------------------------------------------
version: '3'
#all port number should be exposed appending 9
services:

  apim:
    image: deebendu/apim:latest
    container_name: apim
    restart: on-failure
    ports:
      - "8765:8765"
    volumes:
      - ${DATA}/gateway/config:/opt/service/config
      - ${DATA}/gateway/certs:/opt/service/certs
      - ${DATA}/gateway/trace:/opt/service/trace
    networks:
      - portainer

  apim-admin:
    image: deebendu/apim-admin:latest
    container_name: apim-admin
    restart: on-failure
    ports:
      - "8022:8022"
    volumes:
      - ${DATA}/admin/config:/opt/service/config
      - ${DATA}/admin/certs:/opt/service/certs
      - ${DATA}/admin/trace:/opt/service/trace
    networks:
      - portainer

#  react-apim:
#    image: deebendu/react-apim:latest
#    container_name: react-apim
#    restart: on-failure
#    ports:
#      - "8000:8000"
#    volumes:
#      - ${DATA}/apimui/conf.d:/etc/nginx/conf.d
#    networks:
#      - portainer

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true
